FROM python:3.7
RUN pip install yoyo-migrations
RUN pip install psycopg2
RUN apt-get update && apt-get install -y netcat
COPY migrations /migrations
COPY scripts /scripts
COPY yoyo.ini yoyo.ini
ENTRYPOINT ["bash", "scripts/wait_and_migrate.sh"]