version: '2'

services:
  simulation_app:
    build: .
    ports:
      - "5000:5000"
    container_name: tourism_simulation_service
    depends_on:
      - database

  database:
    container_name: tourism_database
    image: postgres:12
    environment:
      POSTGRES_DB: tourism
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    external:
      name: internal