McDonald's:
    x: 426
    y: 711
    name: "MC Donald Main Square"
    coordinates: "426,711,440,681,510,721,492,753"
    shape: "poly"
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Restaurant'


Wawel:
    x: 223
    y: 1911
    name: "Wawel Castle"
    coordinates: "223,1911,181,2013,165,2120,181,2178,229,2250,284,2320,402,2314,498,2248,596,2194,658,2158,732,2110,816,2061,734,1981,680,1915,654,1873,520,1839,470,1833"
    shape: "poly"
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

StMary:
    x: 947
    y: 759
    name: "St. Mary's Basilica"
    coordinates: "947,759,808,821"
    shape: "rect"
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

Sukiennice:
    x: 223
    y: 1911
    name: "Sukiennice"
    coordinates: "678,699,600,839,642,871,718,725"
    shape: "poly"
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'


Wolnica:
    x: 223
    y: 1911
    name: "Wolnica Square"
    coordinates: "1305,2923,1397,2903,1411,2991,1325,3021"
    shape: "poly"
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'