McDonald's:
    x: -660
    y: 1077
    coordinates:
    shape:
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Restaurant'

Sukiennice:
    x: -480
    y: 990
    attractiveness: 9
    price: 0
    people_limit: 50
    time_needed: 20
    time_open: '10:00'
    time_close: '18:00'
    poi_type: 'Heritage'

Polonia Wax Museum:
    x: -571
    y: 1125
    attractiveness: 2
    price: 8
    people_limit: 50
    time_needed: 50
    time_open: '09:00'
    time_close: '22:00'
    poi_type: 'Museum'

Bobby Burger:
    x: -540
    y: 1195
    attractiveness: 5
    price: 5
    people_limit: 30
    time_needed: 20
    time_open: '11:00'
    time_close: '23:59'
    poi_type: 'Restaurant'

Bazylika Mariacka:
    x: -315
    y: 982
    attractiveness: 9
    price: 0
    people_limit: 30
    time_needed: 20
    time_open: '11:00'
    time_close: '18:00'
    poi_type: 'Heritage'

Pomnik Adama Mickiewicza:
    x: -410
    y: 955
    attractiveness: 8
    price: 0
    people_limit: 80
    time_needed: 10
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

Pijalnia Czekolady E. Wedel:
    x: -315
    y: 1075
    attractiveness: 7
    price: 7
    people_limit: 80
    time_needed: 60
    time_open: '09:00'
    time_close: '23:59'
    poi_type: 'Restaurant'

Kosciol Swietego Wojciecha:
    x: -440
    y: 851
    attractiveness: 9
    price: 0
    people_limit: 40
    time_needed: 20
    time_open: '11:00'
    time_close: '18:00'
    poi_type: 'Heritage'

Wieza Ratuszowa:
    x: -584
    y: 954
    attractiveness: 8
    price: 0
    people_limit: 20
    time_needed: 10
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

Klub Kulturalny:
    x: -835
    y: 1206
    attractiveness: 8
    price: 3
    people_limit: 50
    time_needed: 120
    time_open: '00:01'
    time_close: '07:00'
    poi_type: 'Club'

BaniaLuka:
    x: -735
    y: 1140
    attractiveness: 7
    price: 2
    people_limit: 70
    time_needed: 30
    time_open: '12:00'
    time_close: '23:59'
    poi_type: 'Club'

Teatro Cubano:
    x: -745
    y: 1102
    attractiveness: 7
    price: 6
    people_limit: 100
    time_needed: 140
    time_open: '00:01'
    time_close: '07:00'
    poi_type: 'Club'

Galeria Sztuki Bunkier:
    x: -842
    y: 1272
    attractiveness: 7
    price: 7
    people_limit: 40
    time_needed: 80
    time_open: '11:00'
    time_close: '21:00'
    poi_type: 'Museum'

Plac Szczepanski:
    x: -690
    y: 1350
    attractiveness: 8
    price: 0
    people_limit: 50
    time_needed: 10
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

Muzeum Bursztynu:
    x: -372
    y: 1175
    attractiveness: 8
    price: 8
    people_limit: 20
    time_needed: 60
    time_open: '10:00'
    time_close: '20:00'
    poi_type: 'Museum'

Lost Souls Alley:
    x: -215
    y: 1180
    attractiveness: 9
    price: 0
    people_limit: 50
    time_needed: 30
    time_open: '12:00'
    time_close: '20:00'
    poi_type: 'Heritage'

Kamienica Hipolitow:
    x: -164
    y: 1003
    attractiveness: 9
    price: 0
    people_limit: 50
    time_needed: 30
    time_open: '10:00'
    time_close: '17:30'
    poi_type: 'Museum'

Auschwitz Tours:
    x: -78
    y: 960
    attractiveness: 6
    price: 10
    people_limit: 20
    time_needed: 360
    time_open: '09:00'
    time_close: '21:00'
    poi_type: 'Museum'

Milkbar Tomasza:
    x: -20
    y: 1096
    attractiveness: 8
    price: 4
    people_limit: 50
    time_needed: 40
    time_open: '09:00'
    time_close: '20:00'
    poi_type: 'Restaurant'

Muzeum Historyczne Miasta Krakowa:
    x: -416
    y: 1050
    attractiveness: 9
    price: 4
    people_limit: 20
    time_needed: 80
    time_open: '10:00'
    time_close: '20:00'
    poi_type: 'Museum'

Kamienica Szolayskich:
    x: -620
    y: 1310
    attractiveness: 9
    price: 4
    people_limit: 25
    time_needed: 50
    time_open: '10:00'
    time_close: '18:00'
    poi_type: 'Museum'

Kuchnia U Babci Maliny:
    x: -374
    y: 1465
    attractiveness: 5
    price: 6
    people_limit: 30
    time_needed: 40
    time_open: '11:00'
    time_close: '21:30'
    poi_type: 'Restaurant'

Muzeum XX. Czartoryskich:
    x: -208
    y: 1508
    attractiveness: 9
    price: 6
    people_limit: 40
    time_needed: 70
    time_open: '10:00'
    time_close: '15:30'
    poi_type: 'Museum'

Brama Florianska:
    x: -35
    y: 1522
    attractiveness: 9
    price: 0
    people_limit: 20
    time_needed: 15
    time_open: '08:00'
    time_close: '18:00'
    poi_type: 'Heritage'


Barbakan Krakowski:
    x: 17
    y: 1640
    attractiveness: 8
    price: 0
    people_limit: 40
    time_needed: 10
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

Teatr im. Juliusza Slowackiego:
    x: 105
    y: 1380
    attractiveness: 9
    price: 0
    people_limit: 40
    time_needed: 20
    time_open: '11:00'
    time_close: '21:00'
    poi_type: 'Heritage'

Klasztor Siostr Dominikanek:
    x: 102
    y: 870
    attractiveness: 8
    price: 0
    people_limit: 30
    time_needed: 20
    time_open: '11:00'
    time_close: '18:00'
    poi_type: 'Heritage'

Planty:
    x: 108
    y: 765
    attractiveness: 8
    price: 0
    people_limit: 100
    time_needed: 20
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

Rynek Glowny:
    x: -525
    y: 1040
    attractiveness: 10
    price: 0
    people_limit: 150
    time_needed: 10
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'

Starbucks:
    x: -675
    y: 951
    attractiveness: 7
    price: 8
    people_limit: 30
    time_needed: 30
    time_open: '08:00'
    time_close: '22:00'
    poi_type: 'Restaurant'

Lustrzany Labirynt:
    x: -432
    y: 660
    attractiveness: 5
    price: 0
    people_limit: 40
    time_needed: 30
    time_open: '10:00'
    time_close: '22:00'
    poi_type: 'Other'

Klasztor Ojcow Dominikanow:
    x: -318
    y: 625
    attractiveness: 9
    price: 0
    people_limit: 20
    time_needed: 20
    time_open: '11:00'
    time_close: '18:00'
    poi_type: 'Heritage'

Okno Papieskie:
    x: -700
    y: 612
    attractiveness: 6
    price: 0
    people_limit: 20
    time_needed: 10
    time_open: '11:00'
    time_close: '18:00'
    poi_type: 'Heritage'

Muzeum Uniwersytetu Jagiellonskiego:
    x: -835
    y: 960
    attractiveness: 8
    price: 0
    people_limit: 40
    time_needed: 30
    time_open: '10:00'
    time_close: '17:40'
    poi_type: 'Museum'

Posag Mikolaja Kopernika:
    x: -940
    y: 918
    attractiveness: 6
    price: 0
    people_limit: 20
    time_needed: 10
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'