McDonald's:
    x: -660
    y: 1077
    name: "MC Donald Main Square"
    coordinates: "426,711,440,681,510,721,492,753"
    shape: "poly"
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Restaurant'

Sukiennice:
    x: -480
    y: 990
    name: "Sukiennice"
    coordinates: "678,699,600,839,642,871,718,725"
    shape: "poly"
    attractiveness: 6 #(google maps rating -2.5) * 4
    price: 2 #1-10
    people_limit: 80
    time_needed: 20 #in minutes
    time_open: '00:01'
    time_close: '23:59'
    poi_type: 'Heritage'
